name: Close All Pull Requests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: crondaemon/close-pr@v1
      with:
        comment: "Pull request fechado para proteger a branch principal :)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}